# coding: utf-8

"""
    Diffbot Enhance Service

    Enhance is an API to find a person or organization in the Knowledge Graph using partial data  # noqa: E501

    The version of the OpenAPI document: v3.0.0
    Contact: support@diffbot.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import diffbot_enhance_client
from diffbot_enhance_client.api.bulk_enhance_endpoint_api import BulkEnhanceEndpointApi  # noqa: E501
from diffbot_enhance_client.rest import ApiException


class TestBulkEnhanceEndpointApi(unittest.TestCase):
    """BulkEnhanceEndpointApi unit test stubs"""

    def setUp(self):
        self.api = diffbot_enhance_client.api.bulk_enhance_endpoint_api.BulkEnhanceEndpointApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_bulkjob_status(self):
        """Test case for bulkjob_status

        Bulk Enhance Status Endpoint  # noqa: E501
        """
        pass

    def test_enhance_bulkjob(self):
        """Test case for enhance_bulkjob

        Bulk Enhance Endpoint  # noqa: E501
        """
        pass

    def test_poll_bulkjob(self):
        """Test case for poll_bulkjob

        Bulk Enhance Poll Endpoint  # noqa: E501
        """
        pass

    def test_stop_bulkjob(self):
        """Test case for stop_bulkjob

        Bulkjob stop  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
