# coding: utf-8

"""
    Diffbot Enhance Service

    Enhance is an API to find a person or organization in the Knowledge Graph using partial data  # noqa: E501

    The version of the OpenAPI document: v3.0.0
    Contact: support@diffbot.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import enhance_client
from enhance_client.models.request_error import RequestError  # noqa: E501
from enhance_client.rest import ApiException


class TestRequestError(unittest.TestCase):
    """RequestError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestError(self):
        """Test RequestError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = enhance_client.models.request_error.RequestError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
