# coding: utf-8

"""
    Diffbot Enhance Service

    Enhance is an API to find a person or organization in the Knowledge Graph using partial data  # noqa: E501

    The version of the OpenAPI document: v3.0.0
    Contact: support@diffbot.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from diffbot_enhance.configuration import Configuration


class BulkjobStatus(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'job_id': 'str',
        'message': 'str',
        'jobs_total': 'int',
        'jobs_completed': 'int',
        'status': 'str',
        'estimate_remaining_time': 'int'
    }

    attribute_map = {
        'job_id': 'job_id',
        'message': 'message',
        'jobs_total': 'jobs_total',
        'jobs_completed': 'jobs_completed',
        'status': 'status',
        'estimate_remaining_time': 'estimate_remaining_time'
    }

    def __init__(self, job_id=None, message=None, jobs_total=None, jobs_completed=None, status=None, estimate_remaining_time=None, local_vars_configuration=None):  # noqa: E501
        """BulkjobStatus - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._job_id = None
        self._message = None
        self._jobs_total = None
        self._jobs_completed = None
        self._status = None
        self._estimate_remaining_time = None
        self.discriminator = None

        if job_id is not None:
            self.job_id = job_id
        if message is not None:
            self.message = message
        if jobs_total is not None:
            self.jobs_total = jobs_total
        if jobs_completed is not None:
            self.jobs_completed = jobs_completed
        if status is not None:
            self.status = status
        if estimate_remaining_time is not None:
            self.estimate_remaining_time = estimate_remaining_time

    @property
    def job_id(self):
        """Gets the job_id of this BulkjobStatus.  # noqa: E501

        Bulkjob Id  # noqa: E501

        :return: The job_id of this BulkjobStatus.  # noqa: E501
        :rtype: str
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id):
        """Sets the job_id of this BulkjobStatus.

        Bulkjob Id  # noqa: E501

        :param job_id: The job_id of this BulkjobStatus.  # noqa: E501
        :type: str
        """

        self._job_id = job_id

    @property
    def message(self):
        """Gets the message of this BulkjobStatus.  # noqa: E501

        Bulkjob status message  # noqa: E501

        :return: The message of this BulkjobStatus.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this BulkjobStatus.

        Bulkjob status message  # noqa: E501

        :param message: The message of this BulkjobStatus.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def jobs_total(self):
        """Gets the jobs_total of this BulkjobStatus.  # noqa: E501

        Number of jobs in bulkjob  # noqa: E501

        :return: The jobs_total of this BulkjobStatus.  # noqa: E501
        :rtype: int
        """
        return self._jobs_total

    @jobs_total.setter
    def jobs_total(self, jobs_total):
        """Sets the jobs_total of this BulkjobStatus.

        Number of jobs in bulkjob  # noqa: E501

        :param jobs_total: The jobs_total of this BulkjobStatus.  # noqa: E501
        :type: int
        """

        self._jobs_total = jobs_total

    @property
    def jobs_completed(self):
        """Gets the jobs_completed of this BulkjobStatus.  # noqa: E501

        Number of jobs completed in bulkjob.  # noqa: E501

        :return: The jobs_completed of this BulkjobStatus.  # noqa: E501
        :rtype: int
        """
        return self._jobs_completed

    @jobs_completed.setter
    def jobs_completed(self, jobs_completed):
        """Sets the jobs_completed of this BulkjobStatus.

        Number of jobs completed in bulkjob.  # noqa: E501

        :param jobs_completed: The jobs_completed of this BulkjobStatus.  # noqa: E501
        :type: int
        """

        self._jobs_completed = jobs_completed

    @property
    def status(self):
        """Gets the status of this BulkjobStatus.  # noqa: E501

        Status of Bulkjob. One of {NOT_STARTED, IN_PROCESS, COMPLETE, COMPLETE_WITH_FAILURES, STOPPED, ERROR_FINALIZING, UNKNOWN}  # noqa: E501

        :return: The status of this BulkjobStatus.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this BulkjobStatus.

        Status of Bulkjob. One of {NOT_STARTED, IN_PROCESS, COMPLETE, COMPLETE_WITH_FAILURES, STOPPED, ERROR_FINALIZING, UNKNOWN}  # noqa: E501

        :param status: The status of this BulkjobStatus.  # noqa: E501
        :type: str
        """
        allowed_values = ["NOT_STARTED", "IN_PROCESS", "COMPLETE", "COMPLETE_WITH_FAILURES", "STOPPED", "ERROR_FINALIZING", "UNKNOWN"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and status not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def estimate_remaining_time(self):
        """Gets the estimate_remaining_time of this BulkjobStatus.  # noqa: E501

        Estimated remaining time for bulkjob to complete (in seconds). `null` if job is completed or not started.  # noqa: E501

        :return: The estimate_remaining_time of this BulkjobStatus.  # noqa: E501
        :rtype: int
        """
        return self._estimate_remaining_time

    @estimate_remaining_time.setter
    def estimate_remaining_time(self, estimate_remaining_time):
        """Sets the estimate_remaining_time of this BulkjobStatus.

        Estimated remaining time for bulkjob to complete (in seconds). `null` if job is completed or not started.  # noqa: E501

        :param estimate_remaining_time: The estimate_remaining_time of this BulkjobStatus.  # noqa: E501
        :type: int
        """

        self._estimate_remaining_time = estimate_remaining_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BulkjobStatus):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, BulkjobStatus):
            return True

        return self.to_dict() != other.to_dict()
