# coding: utf-8

"""
    Diffbot Enhance Service

    Enhance is an API to find a person or organization in the Knowledge Graph using partial data  # noqa: E501

    The version of the OpenAPI document: v3.0.0
    Contact: support@diffbot.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from diffbot_enhance_client.configuration import Configuration


class RequestError(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'error': 'bool',
        'code': 'int',
        'message': 'str',
        'query': 'object'
    }

    attribute_map = {
        'error': 'error',
        'code': 'code',
        'message': 'message',
        'query': 'query'
    }

    def __init__(self, error=None, code=None, message=None, query=None, local_vars_configuration=None):  # noqa: E501
        """RequestError - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._error = None
        self._code = None
        self._message = None
        self._query = None
        self.discriminator = None

        if error is not None:
            self.error = error
        if code is not None:
            self.code = code
        if message is not None:
            self.message = message
        if query is not None:
            self.query = query

    @property
    def error(self):
        """Gets the error of this RequestError.  # noqa: E501

        Always `true`  # noqa: E501

        :return: The error of this RequestError.  # noqa: E501
        :rtype: bool
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this RequestError.

        Always `true`  # noqa: E501

        :param error: The error of this RequestError.  # noqa: E501
        :type: bool
        """

        self._error = error

    @property
    def code(self):
        """Gets the code of this RequestError.  # noqa: E501

        Error code (same as the HTTP status code)  # noqa: E501

        :return: The code of this RequestError.  # noqa: E501
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this RequestError.

        Error code (same as the HTTP status code)  # noqa: E501

        :param code: The code of this RequestError.  # noqa: E501
        :type: int
        """

        self._code = code

    @property
    def message(self):
        """Gets the message of this RequestError.  # noqa: E501

        Error message  # noqa: E501

        :return: The message of this RequestError.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this RequestError.

        Error message  # noqa: E501

        :param message: The message of this RequestError.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def query(self):
        """Gets the query of this RequestError.  # noqa: E501

        Submitted Enhance query  # noqa: E501

        :return: The query of this RequestError.  # noqa: E501
        :rtype: object
        """
        return self._query

    @query.setter
    def query(self, query):
        """Sets the query of this RequestError.

        Submitted Enhance query  # noqa: E501

        :param query: The query of this RequestError.  # noqa: E501
        :type: object
        """

        self._query = query

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RequestError):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RequestError):
            return True

        return self.to_dict() != other.to_dict()
